<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>1</string>
			<string>2</string>
			<string>3</string>
			<string>4</string>
			<string>5</string>
			<string>6</string>
			<string>7</string>
			<string>8</string>
			<string>9</string>
		</array>
		<key>name</key>
		<string>Troff</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>comment.line.quote.troff</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^(\.\\".*)$</string>
				<key>name</key>
				<string>comment.troff</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.other.troff</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\.(\w+)$</string>
				<key>name</key>
				<string>operand.troff</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.other.troff</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>variable.parameter.troff</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\.(\w+)\s+([^\"].*[^\"])$</string>
				<key>name</key>
				<string>operand.troff</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.other.troff</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>string.interpolated.troff</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\.(\w+)\s+([\"].*[\"])$</string>
				<key>name</key>
				<string>operand.troff</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.other.troff</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>string.interpolated.troff</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\.(\w+)\s+(["].*["])$</string>
				<key>name</key>
				<string>operand.troff</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>text.troff</string>
		<key>uuid</key>
		<string>ca03e751-04ef-4330-9a6b-9b99aae1c418</string>
	</dict>
</plist>